services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - service-link
    networks:
      - app-network
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: link_storage
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      # Проверяем готовность через pg_isready
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s   # Частота проверок
      timeout: 5s    # Таймаут одной проверки
      retries: 10    # Количество попыток перед признанием "healthy"
      start_period: 10s # Время на старт, пока проверки могут не учитываться
    networks:
      - app-network

  service-link:
    build: .
    ports:
      - "8080"
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      replicas: 3
    networks:
      - app-network

    environment:
    - PORT=8080
    - DB_HOST=postgres
    - DB_PORT=5432
    - DB_USER=postgres
    - DB_PASSWORD=password
    - DB_NAME=link_storage
  
networks:
  app-network:
    driver: bridge