events { worker_connections 1024; }

http {
    upstream service-link_servers {
        server service-link:8080; # Docker DNS автоматически распределяет нагрузку на все реплики
    }

    server {
        listen 80;

        location / {
            proxy_pass http://service-link_servers;
        }
    }
}